/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authVerifyOtpRouteImport } from './routes/(auth)/verify-otp'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appTransactionIndexRouteImport } from './routes/(app)/transaction/index'
import { Route as appReportIndexRouteImport } from './routes/(app)/report/index'
import { Route as appCategoryIndexRouteImport } from './routes/(app)/category/index'
import { Route as appTransactionAddRouteImport } from './routes/(app)/transaction/add'
import { Route as appCategoryAddRouteImport } from './routes/(app)/category/add'
import { Route as appTransactionIdEditRouteImport } from './routes/(app)/transaction/$id.edit'
import { Route as appCategoryIdEditRouteImport } from './routes/(app)/category/$id.edit'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authVerifyOtpRoute = authVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appTransactionIndexRoute = appTransactionIndexRouteImport.update({
  id: '/transaction/',
  path: '/transaction/',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportIndexRoute = appReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoryIndexRoute = appCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => appRouteRoute,
} as any)
const appTransactionAddRoute = appTransactionAddRouteImport.update({
  id: '/transaction/add',
  path: '/transaction/add',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoryAddRoute = appCategoryAddRouteImport.update({
  id: '/category/add',
  path: '/category/add',
  getParentRoute: () => appRouteRoute,
} as any)
const appTransactionIdEditRoute = appTransactionIdEditRouteImport.update({
  id: '/transaction/$id/edit',
  path: '/transaction/$id/edit',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoryIdEditRoute = appCategoryIdEditRouteImport.update({
  id: '/category/$id/edit',
  path: '/category/$id/edit',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/': typeof appIndexRoute
  '/category/add': typeof appCategoryAddRoute
  '/transaction/add': typeof appTransactionAddRoute
  '/category': typeof appCategoryIndexRoute
  '/report': typeof appReportIndexRoute
  '/transaction': typeof appTransactionIndexRoute
  '/category/$id/edit': typeof appCategoryIdEditRoute
  '/transaction/$id/edit': typeof appTransactionIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/': typeof appIndexRoute
  '/category/add': typeof appCategoryAddRoute
  '/transaction/add': typeof appTransactionAddRoute
  '/category': typeof appCategoryIndexRoute
  '/report': typeof appReportIndexRoute
  '/transaction': typeof appTransactionIndexRoute
  '/category/$id/edit': typeof appCategoryIdEditRoute
  '/transaction/$id/edit': typeof appTransactionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/category/add': typeof appCategoryAddRoute
  '/(app)/transaction/add': typeof appTransactionAddRoute
  '/(app)/category/': typeof appCategoryIndexRoute
  '/(app)/report/': typeof appReportIndexRoute
  '/(app)/transaction/': typeof appTransactionIndexRoute
  '/(app)/category/$id/edit': typeof appCategoryIdEditRoute
  '/(app)/transaction/$id/edit': typeof appTransactionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/verify-otp'
    | '/'
    | '/category/add'
    | '/transaction/add'
    | '/category'
    | '/report'
    | '/transaction'
    | '/category/$id/edit'
    | '/transaction/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/verify-otp'
    | '/'
    | '/category/add'
    | '/transaction/add'
    | '/category'
    | '/report'
    | '/transaction'
    | '/category/$id/edit'
    | '/transaction/$id/edit'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(auth)/verify-otp'
    | '/(app)/'
    | '/(app)/category/add'
    | '/(app)/transaction/add'
    | '/(app)/category/'
    | '/(app)/report/'
    | '/(app)/transaction/'
    | '/(app)/category/$id/edit'
    | '/(app)/transaction/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/transaction/': {
      id: '/(app)/transaction/'
      path: '/transaction'
      fullPath: '/transaction'
      preLoaderRoute: typeof appTransactionIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/report/': {
      id: '/(app)/report/'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof appReportIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/category/': {
      id: '/(app)/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof appCategoryIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/transaction/add': {
      id: '/(app)/transaction/add'
      path: '/transaction/add'
      fullPath: '/transaction/add'
      preLoaderRoute: typeof appTransactionAddRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/category/add': {
      id: '/(app)/category/add'
      path: '/category/add'
      fullPath: '/category/add'
      preLoaderRoute: typeof appCategoryAddRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/transaction/$id/edit': {
      id: '/(app)/transaction/$id/edit'
      path: '/transaction/$id/edit'
      fullPath: '/transaction/$id/edit'
      preLoaderRoute: typeof appTransactionIdEditRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/category/$id/edit': {
      id: '/(app)/category/$id/edit'
      path: '/category/$id/edit'
      fullPath: '/category/$id/edit'
      preLoaderRoute: typeof appCategoryIdEditRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appCategoryAddRoute: typeof appCategoryAddRoute
  appTransactionAddRoute: typeof appTransactionAddRoute
  appCategoryIndexRoute: typeof appCategoryIndexRoute
  appReportIndexRoute: typeof appReportIndexRoute
  appTransactionIndexRoute: typeof appTransactionIndexRoute
  appCategoryIdEditRoute: typeof appCategoryIdEditRoute
  appTransactionIdEditRoute: typeof appTransactionIdEditRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appCategoryAddRoute: appCategoryAddRoute,
  appTransactionAddRoute: appTransactionAddRoute,
  appCategoryIndexRoute: appCategoryIndexRoute,
  appReportIndexRoute: appReportIndexRoute,
  appTransactionIndexRoute: appTransactionIndexRoute,
  appCategoryIdEditRoute: appCategoryIdEditRoute,
  appTransactionIdEditRoute: appTransactionIdEditRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
